# Generated by Django 5.0.3 on 2024-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.TextField(max_length=60)),
                ('type', models.TextField(max_length=60)),
                ('productName', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
