# Generated by Django 5.0.3 on 2024-05-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventory'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='brand',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='type',
            field=models.CharField(max_length=60),
        ),
    ]
