# Generated by Django 5.0.3 on 2024-05-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksWeb', '0002_alter_inventory_options_alter_inventory_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='productName',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
