# Generated by Django 5.0.3 on 2024-05-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksWeb', '0003_alter_inventory_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AddField(
            model_name='inventory',
            name='desc',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(default=299.99),
        ),
        migrations.AddField(
            model_name='inventory',
            name='productId',
            field=models.CharField(default='AI-1', max_length=60, primary_key=True, serialize=False),
        ),
    ]
