# Generated by Django 5.0.3 on 2024-05-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksWeb', '0005_alter_inventory_desc_alter_inventory_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='productId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
