# Generated by Django 5.0.3 on 2024-05-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksWeb', '0006_alter_inventory_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='productId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
