# Generated by Django 5.0.3 on 2024-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksWeb', '0007_alter_inventory_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='productId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
