# Generated by Django 5.0.3 on 2024-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocksWeb', '0008_alter_inventory_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='productId',
        ),
        migrations.AddField(
            model_name='inventory',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
